### PR TITLE
Hotfix/pr64 fix version comparison

### LINKED ISSUE #64: Fix Magento version comparison + version number color bug?
Unable to complete the deployment due to this error:

```bash
ArgumentError: Malformed version number string 2.1.5
```

Tracing it back to [`magento2.rb`](https://github.com/davidalger/capistrano-magento2/blob/master/lib/capistrano/magento2.rb#L16) and that maybe the `capture :php` portion of the code isn't returning a string as expected?

```ruby

SSHKit.config.command_map[:magento] = "/usr/bin/env php -f bin/magento --"

module Capistrano
  module Magento2
    module Helpers
      def magento_version
        return Gem::Version::new((capture :php, "-f #{release_path}/bin/magento -- -V").split(' ').pop)
      end

      # ...more methods...
  end
end

```

Looking through the various forks I found [minhnd55/capistrano-magento2 has a solution that works ](https://github.com/minhnd55/capistrano-magento2/commit/1d0e187c5ec0e8c146c41dbdf052df6871f03c30)

I'll have a pull request ready soon to patch the issue.

### PR DESCRIPTION
**Pull request by grafikchaos**
Fixes #64 issue with Magento version comparison. Credit goes to @minhnd92 and [their fork](https://github.com/minhnd55/capistrano-magento2/commit/1d0e187c5ec0e8c146c41dbdf052df6871f03c30)

### CODE REVIEW

**Comment by davidalger** [comment]
Closing as resolved in v0.6.1 via commit 1be6406.

**Comment by grafikchaos** [comment]
Thanks @davidalger for the quick turnaround on getting the version comparison issue resolved. The version comparison seems to work now but there is still the issue of running `composer install` against the `update` directory and assuming that a `composer.json` file exists. Please consider my commit [e812bid](https://github.com/davidalger/capistrano-magento2/pull/65/commits/e812b1dc2061e93ff9daf9042c1caa5b39210212). I can open another pull request for that issue specifically if you'd like.

**Comment by davidalger** [comment]
@grafikchaos My apologies, hadn't noticed the PR addressed multiple issues :)

I am curious, what would cause the update directory to exist, but no composer.json file to be found? Are you using it for something custom?

Either way, I've addressed this in commit 1c4c57f  by updating the existing check to simply check for the `./update/composer.json` file vs the containing directly.

**Comment by davidalger** [comment]
Note, this should be published in 0.6.2 shortly.

**Comment by grafikchaos** [comment]
> I am curious, what would cause the update directory to exist, but no composer.json file to be found? Are you using it for something custom?

The issue was mostly because of my own misreading of the warning message in red and the code that was checking if an `update` directory existed or not. I manually created an empty `update` directory to silence the red warning but then that exposed the issue of trying to run composer against a file that did not exist so I thought a better approach would be to verify if a `composer.json` file existed before trying to run a `composer install`.

> Either way, I've addressed this in commit 1c4c57f by updating the existing check to simply check for the ./update/composer.json file vs the containing directly.

Thanks for adding that in!

**Comment by davidalger** [comment]
@grafikchaos Ok, gotcha. Makes sense.

The reason I have that warning in there is because under normal circumstances the ./update directory should be committed to the project repository. This directory is only created when using composer create-project to initially setup the project. I.e. it's not installed when running composer install later on. 

So if you don't commit it, the ./update directory is missing on production (or stage, or wherever you're deploying to), and it will (I believe) break marketplace functionality.

Let me know if you run into any other issues! :)

**Pull request closed without merging**
